### ISSUE TITLE
Comicvine issue

### ISSUE THREAD

**Issue by SirMartin** [Snd-R/komf#88] opened 2023-08-28 06:21 UTC
Hello,

Thanks for the project.

I am having problems making **komf** work with **Comicvine** (I know it is on beta), I have configured **komf** with **kavita**, and I can see in **komf** container logs, that my calls from the user script in **Kavita** are coming correctly.

But the query is launching to **Comicvine** the komf container is getting a _403_ error, but if I copy the same URL and paste it into the browser I get the correct answer from **Comicvine**.

![image](https://github.com/Snd-R/komf/assets/854646/cd0b5f53-659c-4d17-9275-ad479a9eb556)

![image](https://github.com/Snd-R/komf/assets/854646/6af816cb-2479-421f-9fcf-5ae5d5668c8f)

**Comment by THElegend5** [comment] 2023-08-28 06:29
> Hello,
> 
> Thanks for the project.
> 
> I am having problems making **komf** work with **Comicvine** (I know it is on beta), I have configured **komf** with **kavita**, and I can see in **komf** container logs, that my calls from the user script in **Kavita** are coming correctly.
> 
> But the query is launching to **Comicvine** the komf container is getting a _403_ error, but if I copy the same URL and paste it into the browser I get the correct answer from **Comicvine**.
> 
> ![image](https://github.com/Snd-R/komf/assets/854646/cd0b5f53-659c-4d17-9275-ad479a9eb556)
> 
> ![image](https://github.com/Snd-R/komf/assets/854646/6af816cb-2479-421f-9fcf-5ae5d5668c8f)
> 
> 

Update the version of komf you are using to 0.31.1, this issue was fixed in it.

**Comment by SirMartin** [comment] 2023-08-28 06:59
Thanks, I created my container hours before was updated :smile: , now it works.

The problem is that when I fetch the metadata, only fills the publishing year, but no other fields are filled. I tried also for komga, and I cannot see anything updated, even that I can see in the komf container logs, that info is received from comicvine.

![image](https://github.com/Snd-R/komf/assets/854646/0e41676f-8a8a-45d2-a93a-ca4e0cfb0675)

**Comment by Snd-R** [comment] 2023-09-01 18:23
from your logs it seems like it's updating issue fields like summary authors and others so it should be reflected in komga
Not sure why it's not showing anything for you. Is this the case for every series for you?

**Comment by SirMartin** [comment] 2023-09-03 08:11
They are not reflected, the only change I saw it comes the publisher in some of them and added the link but nothing about writers, authors, etc.

**Comment by Snd-R** [comment] 2024-02-26 13:06
can't reproduce. Feel free to reopen if issue is still persists

**Closed by Snd-R** 2024-02-26 13:06 UTC
