### ISSUE TITLE
Feature request: Allow Komf to write a comicinfo file after fetching metadata

### ISSUE THREAD

**Issue by aeryl1999** [Snd-R/komf#16] opened 2022-10-21 08:57 UTC
If Komf was able to write the fetched metadata fields into a comicinfo.xml or json file this would help with migrating large libraries when copying the sqlite file is not possible. This could also be used a backup in case the db gets corrupted/overwritten. This could also help reduce metadata processing if series with comicinfo files are skipped unless forced.

- This option could be enabled through the application.yml
- The location could be to any set folder though the application.yml (if that's easier to implement than writing it into the series folder)
- It doesn't need to embed it into every cbz, just one copy of the comicinfo is needed

Hope you consider this. Thanks

**Comment by Snd-R** [comment] 2022-10-21 15:26
ComicInfo write is already supported, although not documented or fully tested. You can enable it with
```
komga:
  metadataUpdate:
    mode: "FILE_EMBED"
```
It will only write book level metadata and will only add publisher and authors from series level

I have plans to add series.json file write to series folder. From what I recall, komga reads both ComicInfo.xml and series.json when scanning

**Comment by aeryl1999** [comment] 2022-10-24 19:55
> 

Any plans of adding descriptions and tags? Some series like isekai are hard to differentiate with title and authors alone

**Comment by Snd-R** [comment] 2022-10-28 12:17
description is possible but tags are not part of the spec for either comicInfo.xml or series.json
You'd have to use komga to store your tags

**Comment by Snd-R** [comment] 2022-10-28 16:51
series.json write was added in https://github.com/Snd-R/komf/releases/tag/0.13.0. Check readme for new configuration
For now I don't have plans for adding ComicInfo sidecar to series directory the same way as it's done with series.json as it's not really supported by komga or anything else

**Comment by aeryl1999** [comment] 2022-10-29 01:30
Thanks for the update.
I tried the latest update with modes: [API, COMIC_INFO] but it's returning the following error
`An error occurred while trying to identify series: Request method 'POST' not supported`

**Comment by Snd-R** [comment] 2022-10-29 05:31
Did it work before? I can't reproduce this. What's your config and Is there anything in komf logs? 
The error you describing is usually returned by komga and not komf. 
If you're using userscript for identification check the url of komf

**Comment by aeryl1999** [comment] 2022-10-30 22:33
> Did it work before? I can't reproduce this. What's your config and Is there anything in komf logs? The error you describing is usually returned by komga and not komf. If you're using userscript for identification check the url of komf

nvm. I got it working. Going to use this to insert comicinfo for every series. All it needs now is the description or summary that included in the Anansi-project's [comicinfo schema](https://github.com/anansi-project/comicinfo/blob/main/schema/v2.0/ComicInfo.xsd)

`<xs:element minOccurs="0" maxOccurs="1" default="" name="Summary" type="xs:string" />`

**Comment by Snd-R** [comment] 2022-10-31 10:53
Komf detects volume number by filename. If it can't find volume number it won't set specific metadata for that book and will only set common metadata like in your example

Detection only works for volumes and komf will detect book as volume if filename contains `v<number>` or `t<number>` in the filename

**Comment by Snd-R** [comment] 2022-11-09 16:10
issue seem to have been resolved. Closing

**Closed by Snd-R** 2022-11-09 16:10 UTC
