### ISSUE TITLE
[more][error][error][error]

### ISSUE THREAD

**Issue by ShivamB25** [Snd-R/komf#57] opened 2023-04-29 22:22 UTC
22:21:04.614 [JettyServerThreadPool-985] INFO org.snd.mediaserver.MetadataService -- launching metadata aggregation using [MANGA_UPDATES, ANILIST, YEN_PRESS, KODANSHA, VIZ, BOOK_WALKER]
22:21:04.615 [komf-meta-service-3] INFO org.snd.mediaserver.MetadataService -- searching "押忍！！空手部" using MANGA_UPDATES
22:21:04.615 [komf-meta-service-1] INFO org.snd.mediaserver.MetadataService -- searching "押忍！！空手部" using ANILIST
22:21:04.615 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "押忍！！空手部" using YEN_PRESS
22:21:04.615 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "押忍！！空手部" using KODANSHA
22:21:04.947 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "押忍！！空手部" using VIZ
22:21:04.956 [komf-meta-service-1] INFO org.snd.mediaserver.MetadataService -- searching "Osu!! Karate Bu" using ANILIST
22:21:05.039 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "Osu!! Karate Bu" using VIZ
22:21:05.106 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "Osu!! Karate Bu" using YEN_PRESS
22:21:05.165 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "押忍！！空手部" using BOOK_WALKER
22:21:05.565 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "Osu!! Karate Bu" using BOOK_WALKER
22:21:06.448 [komf-meta-service-3] INFO org.snd.mediaserver.MetadataService -- found match: "Osu!! Karatebu" from MANGA_UPDATES  ProviderSeriesId(id=17066145969)
22:21:06.448 [JettyServerThreadPool-985] WARN io.javalin.Javalin -- Uncaught exception
java.lang.NullPointerException: null
        at org.snd.metadata.providers.kodansha.KodanshaParser.parseSearchResults(KodanshaParser.kt:23)
        at org.snd.metadata.providers.kodansha.KodanshaClient.searchSeries(KodanshaClient.kt:31)
        at org.snd.metadata.providers.kodansha.KodanshaMetadataProvider.matchSeriesMetadata(KodanshaMetadataProvider.kt:52)
        at org.snd.mediaserver.MetadataService$matchSeries$4.invoke(MetadataService.kt:177)
        at org.snd.mediaserver.MetadataService$matchSeries$4.invoke(MetadataService.kt:177)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
        at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:168)
        at org.snd.mediaserver.MetadataService.matchSeries(MetadataService.kt:183)
        at org.snd.mediaserver.MetadataService.aggregateMetadataFromProviders$lambda$29$lambda$28(MetadataService.kt:261)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by dymas-cz** [comment] 2023-05-05 09:13
I am getting the same error on every search. Any update on what the problem is?

**Comment by edgehub-cloud** [comment] 2023-05-05 09:14
> I am getting the same error on every search. Any update on what the problem is?

Disable Kodansha

**Comment by Snd-R** [comment] 2023-05-05 15:32
fixed in https://github.com/Snd-R/komf/releases/tag/0.28.1

**Closed by Snd-R** 2023-05-05 15:32 UTC

**Comment by ShivamB25** [comment] 2023-05-05 19:34
alright
